//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequstForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollectRequstForm()
        {
            this.RequestItems = new HashSet<RequestItem>();
        }
    
        public int reqFormId { get; set; }
        public string requestStatus { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<int> employeeId { get; set; }
        public Nullable<int> ngoId { get; set; }
        public Nullable<int> foodSourceId { get; set; }
    
        public virtual FoodSource FoodSource { get; set; }
        public virtual NGO NGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestItem> RequestItems { get; set; }
    }
}
