//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodItem()
        {
            this.RequestItems = new HashSet<RequestItem>();
        }
    
        public int foodItemId { get; set; }
        public string name { get; set; }
        public Nullable<int> quantity { get; set; }
        public string quantityUnit { get; set; }
        public Nullable<System.DateTime> maxPreservationTime { get; set; }
        public Nullable<int> sourceId { get; set; }
    
        public virtual FoodSource FoodSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestItem> RequestItems { get; set; }
    }
}
